name: currency_converter
description: "test app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ### UI
  cupertino_icons: ^1.0.2

  ### State managment
  flutter_bloc: ^8.1.3

  ### HTTP
  dio: ^5.4.0

  ### DI
  provider: ^6.1.1

  ### Storage
  isar: ^3.1.0+1

  ### Model
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
